name: blueboard
description: Plan your trip.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.16
  shared_preferences: ^0.5.3+4
  json_annotation: ^3.0.0
  flutter_bloc: ^0.21.0
  equatable: 
  get_it:
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.7
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true